/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-23 08:23:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.*;
import java.util.*;

public final class vdochead_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/vdocforcelogin.jsp", Long.valueOf(1697119915000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');

//String aut = request.getHeader("Authorization");
String _username = (String) session.getAttribute("username");
if (_username == null) {
	// String _page = request.getRequestURI();

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("vdoclogin.jsp");
        return;
      }
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
Locale.setDefault(Locale.GERMAN);
DateFormat   df =   DateFormat.getDateTimeInstance(DateFormat.FULL,DateFormat.FULL);
NumberFormat nf = NumberFormat.getInstance(); 

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>VDoc Headline</title>\r\n");
      out.write("<meta http-equiv=\"Refresh\" content=\"600\" URL=\"javascript:location.href=location.href\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=charset=iso-8859-1\">\r\n");
      out.write("<script language=\"JavaScript\" src=\"dhtml.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("function ZeitAnzeigen() {\r\n");
      out.write("var Wochentagname =  new Array(\"So\",\"Mo\",\"Di\",\"Mi\",\"Do\",\"Fr\",\"Sa\");\r\n");
      out.write("\r\n");
      out.write(" var Jetzt = new Date();\r\n");
      out.write(" var Tag = Jetzt.getDate();\r\n");
      out.write(" var Monat = Jetzt.getMonth() + 1;\r\n");
      out.write(" var Jahr = Jetzt.getYear();\r\n");
      out.write(" if(Jahr < 999) Jahr += 1900;\r\n");
      out.write(" var Stunden = Jetzt.getHours();\r\n");
      out.write(" var Minuten = Jetzt.getMinutes();\r\n");
      out.write(" var Sekunden = Jetzt.getSeconds();\r\n");
      out.write(" var WoTag = Jetzt.getDay();\r\n");
      out.write(" var Vortag  = ((Tag < 10) ? \"0\" : \"\");\r\n");
      out.write(" var Vormon  = ((Monat < 10) ? \".0\" : \".\");\r\n");
      out.write(" var Vorstd  = ((Stunden < 10) ? \"0\" : \"\");\r\n");
      out.write(" var Vormin  = ((Minuten < 10) ? \":0\" : \":\");\r\n");
      out.write(" var Vorsek  = ((Sekunden < 10) ? \":0\" : \":\");\r\n");
      out.write(" var Datum = Vortag + Tag + Vormon + Monat  + \".\" + Jahr;\r\n");
      out.write(" var Uhrzeit = Vorstd + Stunden + Vormin + Minuten + Vorsek + Sekunden;\r\n");
      out.write(" var Gesamt = Wochentagname[WoTag] + \", \" + Datum + \", \" + Uhrzeit;\r\n");
      out.write("\r\n");
      out.write(" if(DHTML) {\r\n");
      out.write("   if(NS) setCont(\"id\",\"Uhr\",null,\"<span class=\\\"Uhr\\\">\" + Gesamt + \"<\\/span>\");\r\n");
      out.write("   else   setCont(\"id\",\"Uhr\",null,Gesamt);\r\n");
      out.write(" }\r\n");
      out.write(" else return;\r\n");
      out.write("\r\n");
      out.write(" window.setTimeout(\"ZeitAnzeigen()\",1000);\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">	<!--\r\n");
      out.write("	#RestDerSeite { position:absolute; top:50px; left:10px; }\r\n");
      out.write("	.Uhrx { font-family:Arial; font-size:24px; color:blue; }\r\n");
      out.write("	.RestDerSeite { font-family:Arial; color:black; }\r\n");
      out.write(".HeadLine {  font-size: 14pt; font-weight: bold; font-family: Verdana, Arial, Helvetica, sans-serif}\r\n");
      out.write(".InfoLine {  font-size: 10pt; font-weight: bold; font-family: Verdana, Arial, Helvetica, sans-serif}\r\n");
      out.write(".Uhr      {  font-size: 10pt; font-weight: bold; font-family: Verdana, Arial, Helvetica, sans-serif}\r\n");
      out.write("#Uhr      {	 position: inherit;		top:0px;		left:0px;	}\r\n");
      out.write(".version  {  color : #3366CC; font-weight : bold; text-align: right;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" leftmargin=0 topmargin=0 onLoad=\"window.setTimeout('ZeitAnzeigen()',1000)\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td class=\"HeadLine\"> \r\n");
      out.write("      <div align=\"right\">H&auml;nel</div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td bgcolor=\"#FFFFFF\">&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("    <td class=\"HeadLine\" nowrap> \r\n");
      out.write("      <div align=\"left\">Dokumenten Verwaltung</div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td width=\"12.0%\" bgcolor=\"#00CC66\">&nbsp;</td>\r\n");
      out.write("    <td width=\"1.99%\" bgcolor=\"#FFFFFF\">&nbsp;</td>\r\n");
      out.write("    <td width=\"33.0%\" bgcolor=\"#FF3300\">&nbsp;</td>\r\n");
      out.write("    <td width=\"35.0%\" bgcolor=\"#3366CC\">&nbsp;</td>\r\n");
      out.write("    <td width=\"16.0%\" bgcolor=\"#3399FF\" class=\"version\">Version 3.0.8 &nbsp;</td>\r\n");
      out.write("    <td width=\"1.99%\" bgcolor=\"#FFFF00\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td bgcolor=\"#FFFF00\">&nbsp;</td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td nowrap><span class=\"InfoLine\" id=\"Uhr\" title=\"Das aktuelle Datum + Zeit auf Ihrem Rechner\">&nbsp;</span></td>\r\n");
      out.write("    <td nowrap><span class=\"InfoLine\" title=\"");
      out.print( (String) session.getAttribute("fullname") );
      out.write("\">Angemeldet: ");
      out.print( (String) session.getAttribute("username") );
      out.write("</span></td>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
