angular.module('app', ['contextMenu'])
angular.module('app').
  controller('contextCtrl', function($scope, contextService) {    var count = 3        $scope.select = function() {      angular.element(contextService.targetElement).addClass('selected')    }    $scope.deselect = function() {      angular.element(contextService.targetElement).removeClass('selected')    }
    $scope.addPanel = function() {      $scope.panels.push('Panel '+ $scope.panels.length +': this panel has a custom context menu!')    }
    $scope.createPanels = function() {      createPanels()    }
    $scope.dropPanels = function() {      $scope.panels = new Array()    }
    $scope.dropBomb = function() {      alert('Bomb dropped!')    }    //    $scope.pop = function(typ, pkey, dir, pcanr, powner, pfreigeber){//      var myType = pop(typ, pkey, dir, pcanr, powner, pfreigeber)//      alert("myType=" + myType + " currentPKEY=" + currentPKEY + " currentDIR=" + currentDIR)//    }        $scope.reload = function() {      location.reload(true)    }        $scope.showDir = function() {      doPop("showDir()")    }    $scope.chgDir = function() {      doPop("chgDir()")    }    $scope.crtDir = function() {      doPop("crtDir()")    }    $scope.delDir = function() {      doPop("delDir()")    }    $scope.authDir = function() {      doPop("authDir()")    }    $scope.listDir = function() {      doPop("listDir()")    }    $scope.listOpts = function() {      doPop("listOpts()")    }        $scope.crtDoc = function(ckey,pfad) {      doPop("crtDoc('" + ckey + "','" + pfad + "')")    }    $scope.putDoc = function(ckey,pfad) {      doPop("putDoc('" + ckey + "','" + pfad + "')")    }    $scope.qikDoc = function(ckey,pfad) {      doPop("qikDoc('" + ckey + "','" + pfad + "')")    }    $scope.showDoc = function() {      doPop("showDoc()")    }    $scope.getDoc = function() {      doPop("getDoc()")    }    $scope.chgDoc = function() {      doPop("chgDoc()")    }    $scope.authDoc = function() {      doPop("authDoc()")    }    $scope.chgWvlg = function() {      doPop("chgWvlg()")    }    $scope.delDoc = function() {      doPop("delDoc()")    }        $scope.crtUser = function() {      doPop("crtUser()")    }    $scope.chgUser = function() {      doPop("chgUser()")    }    $scope.delUser = function() {      doPop("delUser()")    }        var doPop = function(func, elem) {      var element = (elem) ? elem : angular.element(contextService.targetElement)      if (element){        var href = element.attr('href')        if (href) {          eval(href)           setTimeout(func,0)        }      }    }
    $scope.goToGithub = function() {      window.open('https://github.com/codekraft-studio')    }
//    function createPanels() {//      $scope.panels = new Array()//      for (var i = 0; i < 3; i++) {//        $scope.panels.push('Panel '+ i+': this panel has a custom context menu but a little creative text!')//      }//    }
//    createPanels();
  })
angular.element(document).ready(function() {  // bootstrap application  angular.bootstrap(document, ['app'])})